name: animationmaker
version: '1.2'
summary: Create animations and export them to a movie or XML file
description: |
  This app can be used to create animated movies based on keyframe animations.
  Parts can be exported and imported to and from XML.

grade: stable
confinement: strict

apps:
  animationmaker:
    command: launcher AnimationMaker
    plugs: [x11,home,unity7]

parts:
  launcher:
    plugin: dump
    prime:
      - /bin/*

  animationmaker:
    source: https://github.com/Artanidos/AnimationMaker.git
    plugin: qmake
    qt-version: qt5
    build-packages:
      - build-essential
      - qt5-default
      - qtbase5-dev-tools
      - qttools5-dev-tools
    after: [desktop-qt5]

